# Harbor drone.
workspace:
  base: /drone
  path: src/github.com/vmware/harbor

pipeline:
  clone:
    image: plugins/git
    tags: true
    recursive: false

  test-and-issue-build:
    image: vmware/harbor-e2e-engine:1.38
    pull: true
    privileged: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      LOG_TEMP_DIR: install-logs
    secrets:
      - drone_server
      - drone_token_inte
      - github_automation_api_key
      - gs_client_email
      - gs_private_key
      - gs_project_id
      - harbor_admin
      - harbor_password
      - mail_pwd
      - npm_password
      - npm_username
    commands:
      - export DOMAIN=${CI_DOMAIN}
      - tests/integration.sh
    when:
      status: success

  notify-slack:
    image: plugins/slack
    webhook: ${SLACK_URL}
    username: drone
    template: >
      build https://ci.vcna.io/vmware/harbor/{{ build.number }} finished with a {{ build.status }} status. Please find logs at https://storage.googleapis.com/harbor-ci-logs/integration_logs_{{ build.number }}_{{ build.commit }}.tar.gz
    when:
      repo: vmware/harbor
      branch: [ master, release-*, refs/tags/* ]
      status: [ failure, success ]

  trigger:
    image: plugins/downstream
    server: https://ci.vcna.io
    token: ${DOWNSTREAM_TOKEN}
    fork: true
    repositories:
       - vmware/vic-product
    when:
      repo: vmware/harbor
      event: [ push, tag ]
      branch: [ master, release-*, refs/tags/* ]
      status: success
